### ISSUE TITLE
Propuesta de dominio

### ISSUE THREAD

**Issue by yahirhdzes** [yahirhdzes/parcial_2#3]
@ingreyeslara 
Propuesta de dominio: BalloonDetails.com
En mi caso seguire utilizando el dominio que usted nos proporciono

**Comment by ingreyeslara** [comment]
![Uploading ba.png…]()

**Comment by ingreyeslara** [comment]
![ba](https://github.com/user-attachments/assets/f5386b2f-0ea4-4cfc-9193-18ceffd462d4)
![ba2](https://github.com/user-attachments/assets/bb518291-bdbf-42b5-b259-b787f5dc7059)
